apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-backend
  namespace: blog-dict
  labels:
    app: blog-backend
    dict.security/enabled: "true"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: blog-backend
  template:
    metadata:
      labels:
        app: blog-backend
    spec:
      containers:
      - name: php
        image: blog-dict-backend:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9000
          name: php-fpm
        env:
        - name: APP_NAME
          valueFrom:
            configMapKeyRef:
              name: laravel-config
              key: APP_NAME
        - name: APP_ENV
          valueFrom:
            configMapKeyRef:
              name: laravel-config
              key: APP_ENV
        - name: APP_DEBUG
          valueFrom:
            configMapKeyRef:
              name: laravel-config
              key: APP_DEBUG
        - name: APP_URL
          valueFrom:
            configMapKeyRef:
              name: laravel-config
              key: APP_URL
        - name: LOG_CHANNEL
          valueFrom:
            configMapKeyRef:
              name: laravel-config
              key: LOG_CHANNEL
        - name: DB_CONNECTION
          valueFrom:
            configMapKeyRef:
              name: laravel-config
              key: DB_CONNECTION
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: laravel-config
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: laravel-config
              key: DB_PORT
        - name: DB_DATABASE
          valueFrom:
            configMapKeyRef:
              name: laravel-config
              key: DB_DATABASE
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: laravel-secrets
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: laravel-secrets
              key: DB_PASSWORD
        - name: APP_KEY
          valueFrom:
            secretKeyRef:
              name: laravel-secrets
              key: APP_KEY
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "200m"
            memory: "256Mi"
        volumeMounts:
        - name: laravel-storage
          mountPath: /var/www/storage
        # DICT - Surveillance
        livenessProbe:
          httpGet:
            path: /api/dict/health
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /api/dict/health
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
      
      # DICT - Sidecar Nginx
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
          name: http
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/conf.d
        - name: laravel-storage
          mountPath: /var/www/storage
        resources:
          limits:
            cpu: "200m"
            memory: "128Mi"
          requests:
            cpu: "100m"
            memory: "64Mi"
      
      # DICT - Sidecar de journalisation
      - name: dict-logger
        image: fluent/fluentd:v1.14-1
        resources:
          limits:
            cpu: "100m"
            memory: "128Mi"
          requests:
            cpu: "50m"
            memory: "64Mi"
        volumeMounts:
        - name: fluentd-config
          mountPath: /fluentd/etc
          readOnly: true
        - name: laravel-storage
          mountPath: /var/www/storage
      
      volumes:
      - name: laravel-storage
        persistentVolumeClaim:
          claimName: laravel-storage-pvc
      - name: nginx-config
        configMap:
          name: nginx-config
      - name: fluentd-config
        configMap:
          name: fluentd-config