apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-frontend
  namespace: blog-dict
  labels:
    app: blog-frontend
    dict.security/enabled: "true"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: blog-frontend
  template:
    metadata:
      labels:
        app: blog-frontend
    spec:
      initContainers:
      - name: init-waf-config
        image: busybox
        command: ['sh', '-c', 'cp /config-readonly/* /config-writable/ && chmod -R 777 /config-writable/']
        volumeMounts:
        - name: waf-nginx-config
          mountPath: /config-readonly
        - name: waf-config-writable
          mountPath: /config-writable
      containers:
      - name: angular
        image: blog-dict-frontend:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8081
          name: http
        resources:
          limits:
            cpu: "200m"
            memory: "256Mi"
          requests:
            cpu: "100m"
            memory: "128Mi"

        livenessProbe:
          httpGet:
            path: /dict/health
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /dict/health
            port: http
          initialDelaySeconds: 5
          periodSeconds: 5
        env:
        - name: BACKEND_API_URL
          value: "http://blog-backend"
  
      # DICT - Sidecar WAF
      - name: dict-waf
        image: owasp/modsecurity-crs:3.3-nginx
        ports:
        - containerPort: 8080
          name: waf
        resources:
          limits:
            cpu: "200m"
            memory: "256Mi"
          requests:
            cpu: "100m"
            memory: "128Mi"
        env:
        - name: BACKEND_UPSTREAM
          value: "localhost:8081"
        - name: MODSEC_AUDIT_LOG_FORMAT 
          value: "JSON"
        - name: MODSEC_AUDIT_LOG_TYPE
          value: "Serial"
        - name: MODSEC_AUDIT_LOG
          value: "/dev/stdout"
        - name: LISTEN_PORT
          value: "8080"
        - name: NGINX_ALWAYS_TLS_REDIRECT
          value: "off"
        volumeMounts:
        - name: waf-config
          mountPath: /etc/modsecurity.d/include
          readOnly: true
        - name: waf-config-writable
          mountPath: /etc/nginx/conf.d/
        - name: waf-config
          mountPath: /etc/nginx/conf.d/ports.conf
          subPath: ports.conf
          readOnly: true
      volumes:
      - name: waf-config
        configMap:
          name: waf-config
      - name: waf-nginx-config
        configMap:
          name: waf-nginx-config
      - name: waf-config-writable
        emptyDir: {}