apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: blog-dict-ingress
  namespace: blog-dict
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    # DICT - Sécurité
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
spec:
  rules:
  - host: blog-dict.local
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: blog-backend
            port:
              number: 80
      - path: /
        pathType: Prefix
        backend:
          service:
            name: blog-frontend
            port:
              number: 80
  - host: grafana.blog-dict.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: dict-grafana
            port:
              number: 3000
  - host: prometheus.blog-dict.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: dict-prometheus
            port:
              number: 9090
  - host: loki.blog-dict.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: loki
            port:
              number: 3100
  - host: phpmyadmin.blog-dict.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: phpmyadmin
            port:
              number: 80