apiVersion: v1
kind: ConfigMap
metadata:
  name: promtail-config
  namespace: blog-dict
data:
  promtail.yaml: |
    server:
      http_listen_port: 9080
      grpc_listen_port: 0

    positions:
      filename: /var/www/storage/positions.yaml

    clients:
      - url: http://loki:3100/loki/api/v1/push

    scrape_configs:
      - job_name: laravel-logs
        static_configs:
          - targets:
              - localhost
            labels:
              job: laravel
              app: blog-dict
              __path__: /var/www/storage/logs/*.log
        pipeline_stages:
          - regex:
              expression: '^\[(?P<timestamp>.*)\] (?P<environment>\w+)\.(?P<level>\w+)\: (?P<message>.*)$'
          - labels:
              timestamp:
              environment:
              level:
          - timestamp:
              source: timestamp
              format: '2006-01-02 15:04:05'