apiVersion: v1
kind: ConfigMap
metadata:
  name: waf-nginx-config
  namespace: blog-dict
data:
  default.conf: |
    server {
        listen 8080;
        listen [::]:8080;
        
        server_name _;
        
        location / {
            proxy_pass http://localhost:80;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }